# Generated by Django 4.2.7 on 2023-12-12 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('roll', models.IntegerField(primary_key=True, serialize=False)),
                ('email_field', models.EmailField(default='Rana gmail.com', max_length=254)),
                ('address', models.TextField(default='Dhaka')),
                ('big_integer_field', models.BigIntegerField()),
                ('binary_field', models.BinaryField()),
                ('date_field', models.DateField()),
                ('date_time_field', models.DateTimeField()),
                ('duration_field', models.DurationField()),
                
            ],
        ),
    ]
